music_directory "/home/kagurazaka-shion/Music/"
#pid_file "/home/kagurazaka-shion/.config/mpd/pid"
db_file "/home/kagurazaka-shion/.config/mpd/db"
state_file "/home/kagurazaka-shion/.config/mpd/state"
playlist_directory "/home/kagurazaka-shion/.config/mpd/playlist"
log_file "/home/kagurazaka-shion/.config/mpd/mpd.log"
bind_to_address         "localhost"
port                    "6601"
filesystem_charset    "UTF-8"
audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
        format          "96000:32:2"
}

audio_output {
	type	"fifo"
        name	"Visualizer feed"
        path	"/tmp/mpd.fifo"
        format	"44100:16:2"
}
